openapi: 3.0.1

info:
  title: Barchart Push Notification Service
  version: v2.3.1
  description: Register and unregister Android and iOS devices; send mobile push notifications to those devices (via APNs and FCM).
  contact:
    name: Barchart Support
    url: https://help.barchart.com/support/home
    email: support@barchart.com

components:
  securitySchemes:
    Jwt-Consumer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The JWT used to register and unregister devices.
    Jwt-Admin:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The JWT used to send notifications and query jobs.

  schemas:
    User:
      type: object
      description: Information that uniquely identifies a user.
      properties:
        id:
          type: string
          description: The unique identifier for the user (within the context). Use "ANONYMOUS" when user is unknown.
          example: abc-12345678
        context:
          type: string
          description: A value assigned to you by Barchart, (e.g. application or customer name).
          example: my-company
      required:
        - id
        - context

    ApnsDevice:
      type: object
      description: Information regarding an iOS device (used to communicate with APNs).
      properties:
        device:
          type: string
          description: The unique identifier for the iOS device (obtained from an instance of the app, installed on an actual device).
          example: 6f2dfb1ee3f636e93fad5189710d4fa92edb8ec13d1e39d1bb9d9acd1286f012
        bundle:
          type: string
          description: The bundle name of a mobile application registered with APNs (used to identify the app, the same value across all devices).
          example: com.barchart.ens
      required:
        - device
        - bundle

    FcmDevice:
      type: object
      description: Information regarding an Android device (used to communicate with FCM).
      properties:
        iid:
          type: string
          description: The Firebase IID (FCM deprecated this field, can be omitted).
          example: ca1GWEasSt-LfySsUq_qhi
        token:
          type: string
          description: The Firebase device token (obtained from an instance of the app, installed on an actual device).
          example: ca1GWEasSt-LfySsUq_qhi:APA91bG4YXRvS5dxzUXnDGDgvAh7aojLqZg_21XeiHloaF2Wxqfioyi7JY1sIiFN_oX2_3ye3cgj1cK2forNFIuyo-YVvDd6iwQISXOwVHeJL34j6SuKcaXqqnikn-cPdZ3gb-iSmasd
        package:
          type: string
          description: The package name of a mobile application registered with FCM (used to identify the app, the same value across all devices).
          example: com.barchart.com
      required:
        - token
        - package

    ApnsRegistration:
      type: object
      description: Information a mobile app installation on a specific iOS device.
      properties:
        user:
          description: The user of the mobile app.
          $ref: '#/components/schemas/User'
        apns:
          description: Data regarding the app, installed on a specific device.
          $ref: '#/components/schemas/ApnsDevice'
        provider:
          type: string
          description: A value assigned to you by Barchart, used to identify keys for communication with APNs. Typically the same as the user's context.
      required:
        - user
        - apns
        - provider

    FcmRegistration:
      type: object
      description: Information a mobile app installation on a specific Android device.
      properties:
        user:
          description: The user of the mobile app.
          $ref: '#/components/schemas/User'
        fcm:
          description: Data regarding the app, installed on a specific device.
          $ref: '#/components/schemas/FcmDevice'
        provider:
          type: string
          description: A value assigned to you by Barchart, used to identify keys for communication with FCM. Typically the same as the user's context.
      required:
        - user
        - fcm
        - provider

    UnregisterRequest:
      type: object
      description: Data used identify a "registration" for deletion.
      properties:
        device:
          type: string
          description: The device token (for APNs) or an IID (for FCM).
          example: ca1GWEasSt-LfySsUq_qhi
        bundle:
          type: string
          description: The bundle name (APNs) or the package name (FCM).
          example: com.barchart.ens
        user:
          type: string
          description: The identifier of the user of the mobile app.
          example: abc-12345678
        context:
          type: string
          description: The "context" of the user of the mobile app.
          example: my-company
      required:
        - device
        - bundle
        - user
        - context

    NotificationForUser:
      type: object
      description: The object required to send a notification to a specific user (across multiple devices).
      properties:
        user:
          type: string
          description: The unique identifier for the user (within the context).
          example: abc-12345678
        context:
          type: string
          description: A value assigned to you by Barchart, (e.g. application or customer name).
          example: my-company
        bundle:
          type: string
          description: The bundle name (APNs) or the package name (FCM).
          example: com.barchart.ens
        notification:
          $ref: '#/components/schemas/NotificationContent'
        development:
          type: boolean
          description: If true, the APNs sandbox is used.
          example: false
      required:
        - user
        - context
        - bundle
        - notification

    NotificationForDevice:
      type: object
      description: The object required to send a notification to a specific device.
      properties:
        device:
          type: string
          description: A device token (for APNs) or an IID (for FCM)
          example: ca1GWEasSt-LfySsUq_qhi
        notification:
          $ref: '#/components/schemas/NotificationContent'
        development:
          type: boolean
          description: If true, the APNs sandbox is used.
          example: false
      required:
        - device
        - notification

    NotificationnForBundle:
      type: object
      description: The object required to send a notification to a bundle (all installations of the app).
      properties:
        bundle:
          type: string
          description: The bundle name (APNs) or the package name (FCM).
          example: com.barchart.ens
        notification:
          $ref: '#/components/schemas/NotificationContent'
        development:
          type: boolean
          description: If true, the APNs sandbox is used.
          example: false
      required:
        - bundle
        - notification

    NotificationContent:
      type: object
      description: The content of a notification (e.g. title, body, etc).
      properties:
        title:
          type: string
          description: The title of the notification.
          example: Test Notification Title
        subtitle:
          type: string
          description: The subtitle of the notification.
          example: Test Notification Subtitle
        body:
          type: string
          description: The content of the notification.
          example: We thought you should know — an important event just happened.
        category:
          type: string
        icon:
          type: string
        image:
          type: string
        sound:
          type: string
        badge:
          type: string
        color:
          type: string
        click_action:
          type: string
        data:
          type: object
          additionalProperties: { }
      required:
        - title

    JobInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The job identifier.
        status:
          type: string
          description: The status of the job (CREATED/DONE/IN_PROGRESS)
        request:
          type: string
          description: The original request which spawned the job.
        scan:
          type: object
          properties:
            last:
              type: string
              description: The last device processed.
        system:
          type: object
          properties:
            created:
              type: number
              description: Date the job was created (milliseconds since epoch).
            updated:
              type: number
              description: Date the job was updated (milliseconds since epoch).
            finished:
              type: number
              description: Date the job finished (milliseconds since epoch).

  responses:
    ErrorResponse:
      description: 'Object with array of errors'
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string

tags:
  - name: v2

servers:
  - url: 'https://push-notifications.aws.barchart.com'
  - url: 'https://push-notifications.stage.aws.barchart.com'

paths:
  /v2/register:
    post:
      summary: Register Device
      description: Register a device for notifications with APNs or FCM.
      tags:
        - v2
      security:
        - Jwt-Consumer: [ ]
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ApnsRegistration'
                - $ref: '#/components/schemas/FcmRegistration'
      responses:
        '200':
          description: Device has been registered.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ApnsRegistration'
                  - $ref: '#/components/schemas/FcmRegistration'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  /v2/unregister:
    post:
      summary: Unregister Device
      description: Deletes registrations for a device.
      tags:
        - v2
      security:
        - Jwt-Consumer: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnregisterRequest'
      responses:
        '200':
          description: Device has been unregistered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'successfully'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  /v2/send:
    post:
      summary: Send push notification(s)
      description: Starts a job to transmit push notification(s) via APNs and/or FCM.
      tags:
        - v2
      security:
        - Jwt-Admin: [ ]
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/NotificationForUser'
                - $ref: '#/components/schemas/NotificationForDevice'
                - $ref: '#/components/schemas/NotificationnForBundle'
      responses:
        '200':
          description: The notification has been scheduled for transmission.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: The identifier of the job responsible for sending the push notification.
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  /v2/job/{id}:
    get:
      summary: Retrieves status of a job to send notification(s).
      description: Retrieves status of a job to send notification(s).
      tags:
        - v2
      security:
        - Jwt-Admin: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: The identifier of the job to query.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: An object with job information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobInfo'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  /v2/service/read:
    get:
      summary: Retrieves metadata regarding the Barchart Push Notification Service.
      description: Retrieves the version of the Barchart Push Notification Service and other metadata.
      tags:
        - v2
      responses:
        '200':
          description: Version of the Barchart Push Notification Service and other metadata.
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the remote service.
                        example: serverless-push-gateway
                      environment:
                        type: string
                        description: The name of the enviroment (e.g. stage or prod).
                        example: prod
                      version:
                        type: string
                        description: The version of the remote service.
                        example: v2.3.0
                      description:
                        type: string
                        description: A description of the remote service.
                        example: Barchart Push Notification Service
